const menu=document.querySelector('.menu-toggle');const nav=document.querySelector('.site-header nav');if(menu&&nav){menu.addEventListener('click',()=>nav.classList.toggle('open'))}

const chaos=document.getElementById('chaos-button'),title=document.getElementById('status-title'),message=document.getElementById('status-message');
const events=[['Everything is under control.','This statement has not been independently verified.'],['Printer negotiation has begun.','The printer requested three sheets of paper and a better work-life balance.'],['Doctor detected.','Doctor is currently looking for a pen.'],['Tea deployment successful.','Morale has increased by approximately 4%.'],['Queue stabilized.','Token 847 has accepted its destiny.'],['Emergency drill complete.','Everyone panicked professionally.'],['System status: suspicious.','Please continue pretending everything is normal.']];
let chaosCount=0;if(chaos){chaos.addEventListener('click',()=>{chaosCount++;const e=events[Math.floor(Math.random()*events.length)];title.textContent=e[0];message.textContent=e[1];chaos.textContent=chaosCount>5?'You have done enough.':'Increase Chaos';saveState()})}

const worldLevel=document.getElementById('world-level'),worldProgress=document.getElementById('world-progress'),worldLog=document.getElementById('world-log');
const worldNames=['Reception Wing','Redstone Lab','Skybridge ICU','Underground Diagnostics','Quantum Pharmacy','Emergency Tower','Tea Research Center','Printer Rehabilitation Block'];
const worldActions=['constructed a suspicious new wing','installed 47 unnecessary buttons','spawned a specialist with no map','opened a corridor to absolutely nowhere'];
let worldState={level:1,progress:0,built:[]};
try{worldState={...worldState,...JSON.parse(localStorage.getItem('hospital-exe-world')||'{}')}}catch{}
function saveWorld(){try{localStorage.setItem('hospital-exe-world',JSON.stringify(worldState))}catch{}}
function renderWorld(){if(!worldLevel)return;worldLevel.textContent='HOSPITAL LEVEL '+String(worldState.level).padStart(2,'0');worldProgress.style.width=Math.min(100,Math.max(8,worldState.progress))+'%';worldLog.textContent=worldState.built.length?'BUILD LOG: '+worldState.built[worldState.built.length-1]: 'BOOT: fictional construction system online.'}
function command(action){if(!worldLevel)return;const name=worldNames[Math.floor(Math.random()*worldNames.length)];if(action==='build'){worldState.built.push(name);worldState.progress+=18;if(worldState.progress>=100){worldState.level++;worldState.progress=0;worldState.built=[];worldLog.textContent='LEVEL UP: the hospital has built something it cannot explain.'}else worldLog.textContent='BUILD: '+name+' '+worldActions[0]+'.'}if(action==='upgrade'){worldState.progress=Math.min(99,worldState.progress+12);worldLog.textContent='UPGRADE: installed technology nobody requested.'}if(action==='spawn'){worldState.progress=Math.min(99,worldState.progress+7);worldLog.textContent='SPAWN: a fictional specialist has entered the wrong department.'}if(action==='incident'){worldState.progress=Math.min(99,worldState.progress+5);worldLog.textContent='INCIDENT: '+worldActions[Math.floor(Math.random()*worldActions.length)]+'.'}saveWorld();renderWorld()}
document.querySelectorAll('[data-command]').forEach(b=>b.addEventListener('click',()=>command(b.dataset.command)));renderWorld();
document.querySelectorAll('.chaos-trigger').forEach(btn=>btn.addEventListener('click',()=>{const replies=['Doctor says: “Please stop asking the website medical questions.”','Doctor is thinking...','Doctor has requested a coffee.','Doctor has left the comic panel.','Doctor says: “Hmm.”'];alert(replies[Math.floor(Math.random()*replies.length)]);}));

const statusEl=document.getElementById('live-status-grid'),statusTitle=document.getElementById('live-status-title'),stamp=document.getElementById('status-timestamp');
const departments=['Cardiology','Neurology','Surgery','Pediatrics','Radiology','Pathology','Emergency','ICU','Pharmacy','Laboratory','Reception','Hospital IT','Cafeteria','Housekeeping','Billing','Patient Transport'];
const states=['OPERATIONAL','BUSY','CALIBRATING','RUNNING SMOOTHLY','SLIGHTLY CONFUSED','AWAITING COFFEE','MONITORING','PROCESSING','FINDING A PEN','UNDER REVIEW'];
const activities=['Queue behaving suspiciously well','Printer has resumed negotiations','Tea reserves detected','Doctor finder has found itself','One elevator is thinking','Forms have multiplied','A clipboard has gone missing','All fictional systems are making noises','Reception has discovered Token 848','The coffee protocol is active','Department meeting has exceeded its meeting','Wi-Fi is emotionally stable'];
function uniqueSample(arr,n){return [...arr].sort(()=>Math.random()-.5).slice(0,n)}
function generateStatus(){if(!statusEl)return;const selected=uniqueSample(departments,8),used=new Set();statusEl.innerHTML=selected.map((dept,i)=>{let state;do{state=states[Math.floor(Math.random()*states.length)]}while(used.has(state));used.add(state);const activity=activities[Math.floor(Math.random()*activities.length)];return '<article class="live-card"><span class="live-number">'+String(i+1).padStart(2,'0')+'</span><div><strong>'+dept+'</strong><b>'+state+'</b><p>'+activity+'.</p></div></article>'}).join('');statusTitle.textContent=uniqueSample(['Fictional systems reporting in','Hospital systems are making noises','All departments have reported something','Command center has achieved maximum normality','Reality check: inconclusive'],1)[0];stamp.textContent='Last fictional update: '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})+' • Auto-refresh: 12 seconds';saveState()}
setInterval(generateStatus,12000);generateStatus();

const STORAGE_KEY='hospital-exe-state-v2';
function saveState(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify({chaosCount,lastStatus:stamp?.textContent||'',savedAt:Date.now()}))}catch{}}
try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(saved?.chaosCount){chaosCount=saved.chaosCount;if(chaos)chaos.textContent=chaosCount>5?'You have done enough.':'Increase Chaos'}}catch{}

let deferredPrompt=null;const installBtn=document.getElementById('install-app');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;if(installBtn)installBtn.hidden=false});installBtn?.addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installBtn.hidden=true});window.addEventListener('appinstalled',()=>{if(installBtn)installBtn.hidden=true});

document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='p')alert('🖨️ PRINTER ALERT: It has developed philosophical differences with paper.');if(e.key.toLowerCase()==='c')alert('💥 CHAOS LEVEL INCREASED BY 17%.')});
setInterval(()=>{if(!document.hidden&&Math.random()<.18){const notes=['🔊 Someone has misplaced the doctor’s pen.','🖨️ Printer status: emotionally unavailable.','☕ Tea has been successfully deployed.','🛗 Elevator has selected a philosophical floor.'];alert(notes[Math.floor(Math.random()*notes.length)])}},15000);

if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));}

/* PLAYABLE HOSPITAL BUILDER */
const GAME_KEY='hospital-exe-builder-v1';
const defaultGame={money:500,staff:3,power:100,chaos:0,level:1,score:0,selected:'reception',tiles:Array(20).fill(null),log:'BOOT: construction permits have been misplaced.'};
let gameState={...defaultGame};try{gameState={...defaultGame,...JSON.parse(localStorage.getItem(GAME_KEY)||'{}')}}catch{}
const gameTiles=document.getElementById('build-grid'),options=document.getElementById('build-options');
const gm=document.getElementById('game-money'),gs=document.getElementById('game-staff'),gp=document.getElementById('game-power'),gc=document.getElementById('game-chaos'),gl=document.getElementById('game-level'),glog=document.getElementById('game-log'),ut=document.getElementById('unlock-title'),ux=document.getElementById('unlock-text'),up=document.getElementById('unlock-progress');
const buildings=[{id:'reception',name:'Reception',icon:'🧑‍💼',cost:50,power:2,staff:0,unlock:1},{id:'lab',name:'Chaos Lab',icon:'🧪',cost:90,power:8,staff:1,unlock:1},{id:'tea',name:'Tea Dept.',icon:'☕',cost:70,power:1,staff:0,unlock:1},{id:'printer',name:'Printer ICU',icon:'🖨️',cost:110,power:12,staff:1,unlock:1},{id:'radiology',name:'Radiology',icon:'🩻',cost:140,power:16,staff:1,unlock:1},{id:'emergency',name:'Emergency Tower',icon:'🚑',cost:180,power:22,staff:2,unlock:2},{id:'pharmacy',name:'Quantum Pharmacy',icon:'💊',cost:220,power:26,staff:2,unlock:3},{id:'icu',name:'Infinite ICU',icon:'🏥',cost:280,power:32,staff:3,unlock:4},{id:'portal',name:'Portal Ward',icon:'🌀',cost:350,power:40,staff:4,unlock:5}];
function saveGame(){try{localStorage.setItem(GAME_KEY,JSON.stringify(gameState))}catch{}}
function unlocked(b){return gameState.level>=b.unlock}
function renderGame(){if(!gameTiles)return;gm.textContent=gameState.money;gs.textContent=gameState.staff;gp.textContent=Math.max(0,gameState.power)+'%';gc.textContent=gameState.chaos;gl.textContent=String(gameState.level).padStart(2,'0');glog.textContent=gameState.log;gameTiles.innerHTML=gameState.tiles.map((id,i)=>{const b=buildings.find(x=>x.id===id);return '<button class="build-tile '+(b?'occupied':'')+'" data-slot="'+i+'">'+(b?'<span class="tile-icon">'+b.icon+'</span><small>'+b.name+'</small>':'<span class="tile-icon">＋</span><small>EMPTY</small>')+'</button>'}).join('');gameTiles.querySelectorAll('.build-tile').forEach(t=>t.addEventListener('click',()=>buildAt(+t.dataset.slot)));const available=buildings.filter(unlocked);options.innerHTML=available.map(b=>'<button class="build-option '+(gameState.selected===b.id?'selected':'')+'" data-build="'+b.id+'"><b>'+b.icon+' '+b.name+'</b><small>💰 '+b.cost+' • ⚡ '+b.power+' • 👥 '+b.staff+'</small></button>').join('');options.querySelectorAll('.build-option').forEach(b=>b.addEventListener('click',()=>{gameState.selected=b.dataset.build;renderGame()}));const next=buildings.find(b=>b.unlock>gameState.level);if(next){ut.textContent='Next unlock: '+next.name;ux.textContent='Reach Level '+next.unlock+' to unlock '+next.name+'.';up.style.width=Math.min(100,((gameState.level-1)/(next.unlock-1))*100)+'%'}else{ut.textContent='ALL SYSTEMS UNLOCKED';ux.textContent='The hospital has become legally unexplainable.';up.style.width='100%'}saveGame()}
function buildAt(slot){if(gameState.tiles[slot]){gameState.log='DEMOLITION DENIED: the building has developed emotional attachment.';renderGame();return}const b=buildings.find(x=>x.id===gameState.selected);if(!b)return;if(gameState.money<b.cost){gameState.log='BUDGET ERROR: the hospital cannot afford '+b.name+'.';renderGame();return}gameState.money-=b.cost;gameState.staff+=b.staff;gameState.power=Math.max(0,gameState.power-b.power);gameState.score+=b.cost;gameState.tiles[slot]=b.id;if(gameState.score>=350*gameState.level){gameState.level++;gameState.money+=120;gameState.log='LEVEL UP: '+b.name+' triggered an unnecessary expansion. BONUS +120.'}else gameState.log='BUILD COMPLETE: '+b.name+' installed. Nobody read the manual.';renderGame()}
document.getElementById('incident-button')?.addEventListener('click',()=>{const incidents=[['🖨️ PRINTER RIOT','The printer has declared independence.',-35,8],['🛗 ELEVATOR PHILOSOPHY','The elevator refuses to visit Floor 2.',-20,6],['☕ TEA SHORTAGE','Staff morale has become theoretical.',-25,10],['🧪 LAB MELTDOWN','The beaker is now the supervisor.',-45,14],['📋 FORM APOCALYPSE','One form became twelve forms.',-15,12]];const e=incidents[Math.floor(Math.random()*incidents.length)];gameState.money=Math.max(0,gameState.money+e[2]);gameState.chaos+=e[3];gameState.log='DISASTER: '+e[0]+' — '+e[1]+' '+e[2]+' budget.';if(gameState.chaos>=50){gameState.level++;gameState.chaos=0;gameState.money+=150;gameState.log+=' CHAOS LEVEL-UP! Emergency funding: +150.'}renderGame()});
document.getElementById('reset-game')?.addEventListener('click',()=>{if(confirm('Erase the fictional hospital and start over?')){gameState={...defaultGame,tiles:Array(20).fill(null)};renderGame()}});
renderGame();
