"""Generate 100 unique Facilities comic incidents from the 20 Python seed comics."""
from pathlib import Path
import json,re

src=Path("js/generated-content.js").read_text(encoding="utf-8")
raw=re.search(r"window\.HOSPITAL_CONTENT\s*=\s*(.*);\s*$",src,re.S).group(1)
data=json.loads(raw)
base=data["facilityComics"]
modes=[
 lambda f,t,p:[f,t+" // INCIDENT LOG",["INCIDENT LOG: "+p[0],"STATUS: "+p[1],"SUPERVISOR: "+p[2],"VERDICT: "+p[3]]],
 lambda f,t,p:[f,t+" // EMERGENCY MEMO",["MEMO: Stop investigating "+t.lower()+".","STAFF: Why?","MEMO: Because "+p[2].lower(),"STAFF: This memo is making things worse."]],
 lambda f,t,p:[f,t+" // OBJECT TESTIMONY",["OBJECT: I would like to testify about "+t.lower()+".","STAFF: Proceed.","OBJECT: "+p[1],"STAFF: That explains absolutely nothing."]],
 lambda f,t,p:[f,t+" // BREAKING NEWS",["BREAKING: "+f+" has reported a "+t.lower()+" situation.","REPORTER: Is anyone concerned?","STAFF: "+p[3],"REPORTER: Excellent. I have more questions."]],
 lambda f,t,p:[f,t+" // MANAGEMENT MEETING",["MANAGEMENT: Agenda item one: "+t.lower()+".","STAFF: We already discussed this.","MANAGEMENT: Yes. The "+f+" version.","CHAIRPERSON: Meeting adjourned before it becomes worse."]]
]
out=[m(f,t,p) for f,t,p in base for m in modes]
assert len(out)==100 and len({json.dumps(x,sort_keys=True) for x in out})==100
data["facilityComics"]=out
Path("js/generated-content.js").write_text("/* AUTO-GENERATED BY tools/generate_facility_comics.py */\nwindow.HOSPITAL_CONTENT = "+json.dumps(data,ensure_ascii=False,separators=(",",":"))+";\n",encoding="utf-8")
print("Generated 100 unique facility comics.")
